Respect thresholds in scaled months
pyrochlore/obsidian-tracker pull request #365
Opened 2024-06-03 04:00 UTC by mkarrmann

# Description

See https://github.com/pyrochlore/obsidian-tracker/issues/364 for description. Ensures that the `month` graph's `threshold` parameter, even when `circleColorByValue` is also used.

Fixes #364

Note that I just raised that issue myself, and it appears that the behavior I'm removing was added intentionally. So, I'd understand if this PR is rejected (although I would be curious to hear *why* it behaves the way it does).

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] If this is a bug fix, did you add or update a test file to the examples directory that verifies the bug is fixed?

2024-06-03 04:00 UTC, mkarrmann commented on examples/TestCalendar.md
> +Use parameters `circleColorByValue`, `yMin`, and `yMax`, to color the circles based on the values
I think it's worth emphasizing that you need to set all 3 of these in order for it to take effect.

2024-06-03 04:01 UTC, mkarrmann commented on examples/diary/Lucas-20210105-Journal.md
> +#exercise-pushup:5
This date should now have no circle, because it is beneath the threshold.

2024-06-03 04:02 UTC, mkarrmann commented
@pyrochlore FYI. I'd be interested to hear your thoughts on this / the underlying issue.

2025-01-05 02:26 UTC, lazyguru requested changes

2025-01-05 02:26 UTC, lazyguru commented on examples/diary/Lucas-20210105-Journal.md
> +#exercise-pushup:5
I see it circled when I test your branch locally

2025-01-05 03:24 UTC, lazyguru commented on examples/diary/Lucas-20210105-Journal.md
> +#exercise-pushup:5
The issue is that you have to update all of the 2021-01-05 files to handle for all the various date formats. When I update 2021-01-05.md, the test works

2025-01-05 03:49 UTC, lazyguru approved these changes

2025-01-05 03:50 UTC, merged

2025-01-05 03:50 UTC, lazyguru commented
I applied the missing fixes. Thanks for your contribution

2025-01-08 05:20 UTC, mkarrmann commented
@lazyguru TY so much!